import {Injectable} from '@angular/core';

@Injectable({
  providedIn: 'root'
})

export class List {
 list = [
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
   {
     title: 'saudiver5-ap-ar',
     brand: 'RCProGold',
     lang: 'ar',
     url: 'https://royal-promotions.co/saudiver5-ap-ar/',
     steps: 1,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/saudiver5-ap-ar.png',
     date: '10.10.18'
   },
   {
     title: 'the-tesler-v2',
     brand: 'S2trade',
     lang: 'ar',
     url: 'http://alpha-promotions.co/the-tesler-v2-ar/',
     steps: 2,
     features: ['bb', 'sticky'],
     description: '',
     image: 'assets/images/funnels/the-tesler.png',
     date: '10.10.18'
   },
 ];
}
